server:
  port: 8081

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
                    # Expense Service
                    - id: notification-service
                      uri: http://localhost:8085
                      predicates:
                        - Path=/api/notification/**
                        - Path=/api/budget/**
                    # Expense Service
                    - id: expense-service
                      uri: http://localhost:8082
                      predicates:
                        - Path=/api/expenses/**

                    # Auth Service
                    - id: auth-service
                      uri: http://localhost:8083
                      predicates:
                        - Path=/api/auth/**

                    # Analytics Service
                    - id: analytics-service
                      uri: http://localhost:8084
                      predicates:
                        - Path=/api/analytics/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
